### ISSUE TITLE
Some questionable code executed on the test site

### ISSUE THREAD

**Issue by ghost** [YagoLopez/ng-dashboard#2]

**Comment by YagoLopez** [comment]
Hello. Can you ellaborate more on this? Did you get this url from a browser debug session? I do not recognize that code as mine. In a debug session you can find out the file that generates this http call, please tell me which it is.

It seems to be some kind of Git-Hub statistics. Take a look at the domain: https://collector.githubapp.com, it belongs to GitHub where the app is hosted.
