### ISSUE TITLE
Typo mistake

### ISSUE THREAD

**Issue by HugoMoy** [YagoLopez/ng-dashboard#3]
Hello, 
There is a typo mistake in the readme with the title : Requierements -> Requirements.
Just so you know :)
Regards,

**Comment by YagoLopez** [comment]
Hey, thank you for your collaboration 😄 

Typo fixed in this commit 👍 
https://github.com/YagoLopez/ng-dashboard/tree/928eca54dbd41508da595cc2d609af005331d9a8
Cheers!
